### ISSUE TITLE
Chord detection only working for C as root (Why is this a feature?!)

### ISSUE THREAD

**Issue by mathaou** [tonaljs/tonal#130]
The docs [here](https://github.com/tonaljs/tonal/tree/master/packages/pcset) say that the 'poor man's chord detection' works on the list of intervals starting from C. In testing this, I was trying to get my program to detect chord inversions, so I gave it a Dm7 (C4, D4, F4, A4) and cycled through trying to find an inversion that the library liked.
```
permutations(arr).map(e => {
    let index = 3;
    let sanitizedArray = e.map(note => {
      let trim = note.replace(/[\d]/gm, '');
      if(trim === 'C') index++; // need to be more sophisticated in future, just for testing
      return `${trim}${index}`;
    });

    let chroma = chordType(pcset(sanitizedArray).chroma);

    if(chroma.name.length > 0) console.log(sanitizedArray);
  });
```

In testing, I found that it only likes specific C chords (C+/ Cdim didn't work, didn't test any complex extensions past maj7). Why does it matter that the list of intervals has to start from C? A collection of intervals [1P, 3M, 5P] will be a major chord no matter where you go, so why is the root note the deciding factor on chord quality? My fix for the moment is to transpose every one of my notes down whatever interval gets me to C as the root, but goodness gracious...

**Comment by danigb** [comment]
Something is broken with that. I'll look into it. Thanks for reporting!

**Comment by thebne** [comment]
@danigb just out of curiosity, why don't you support some more "fancy" chord detection? 

Either a limited one like [this](https://github.com/greird/chordictionaryjs/blob/master/src/chords.js) and [this](https://pypi.org/project/pychord/) - or a more sophisticated version like music21's (I don't like their implementation because it has no runtime boundaries, but that's the most robust implementation I've seen).

Adding to that, in the (allegedly broken) version above there's no way to get the root. So if I use `["C", "E", "G"]` it returns the same as `["G", "E", "C"]` etc.

**Comment by danigb** [comment]
Just because is not easy, and I didn't find time nor energy to write one 🤷‍♀ 

But help with this issue is more than welcome (ideas on how to implement, PRs, comments...)

**Comment by mathaou** [comment]
@danigb Not to knock the work you've already done, but the library I found to work best out of the large handful of different ones I've tried was [mingus](https://bspaans.github.io/python-mingus/). If you have a midi controller you can test out the full capability of its chord detection [here](https://www.mfarstad.com/zodd), but I think they have a really solid way of determining chords. I had to peek/modify the source some in working on that chord detection website, but It's pretty powerful and super cool. Only thing is they have to really ground themselves in super traditional music theory (the 2nd of an D# major scale is E# for example), so I had to throw various mixes of chords at it until I got something that worked (replaced all C's with B# and F with E#), then just sanitized it down to the more friendly enharmonic note and removed all duplicate responses before presenting to the user.

**Comment by danigb** [comment]
@mathaou Thanks for mingus link! 🙏  I liked a lot, looks like a great library. 

And encouraged by that, I've implemented a chord detection mechanism that _hopefully_ works 😅 (it's not based in mungus approach, since tonal uses dictionaries... but it was nice to see other approaches)

So heres the new package: https://github.com/tonaljs/tonal/tree/master/packages/chord-detect

**Comment by thebne** [comment]
@danigb , just wanted to thank you for this logic again.
I finally released some stable-ish version of [my MIDI project](https://github.com/thebne/midiate), and I'm basing my chord detection (along with some other manipulation) solely on this functionality :)  

The only thing I'd consider changing is removing the capital M from the detection (or making it optional), since it's not the standard notation I'm familiar with.
