### ISSUE TITLE
Diatonic chords of any mode?

### ISSUE THREAD

**Issue by jabza** [tonaljs/tonal#216]
Hi, thanks for creating this fantastically useful library.

When using the 'Key' package, the 7 (I, II, III, IV and so on) diatonic chords for major & minor can be seen.

Is it possible to see similar information for the other modes (Lydian, Dorian ect) or perhaps any scale using two half + five full intervals?

Thank you

**Comment by bali182** [comment]
Just wanted to do this myself, it would come very useful to get for a given mode all the chords.

Eg.: given `"C dorian"` -> `["Cmin", "Dmin", "EbMaj", "Fmaj"...]`

It would also pretty interesting to get the extended, double extended etc chords. Just math-wise I can think of doing it by

1. taking the given mode (eg.: dorian)
2. figuring out the relative major (not sure how to do it with the library but doable without)
3. finding the chords for that using `Key.majorKey` function
4. reordering the chords so that it starts with the dorian root (also not sure how to do it with the library)

**Comment by danigb** [comment]
Hi,

You're right. I think that should be part of "Mode" module (Key is focused more in tonal functions, and modes has it's own idiosyncrasies). Let me think something about it 👍

**Comment by danigb** [comment]
I've added a bunch of functions to Mode module: https://github.com/tonaljs/tonal/tree/master/packages/mode#notesmodename-string-tonic-string--string
Let me know if works for you 👍

**Comment by jabza** [comment]
That module looks pretty much perfect, nice one!

The only thing that could possibly be useful is the roman numeral names to go along with it perhaps? As with the Key module
