### ISSUE TITLE
b9sus chord has a M9

### ISSUE THREAD

**Issue by martijnmichel** [tonaljs/tonal#217]
as stated in topic, please correct typo

**Comment by danigb** [comment]
I see... Here the problem is that `b` is interpreted as `B` note, so `b9sus` is interpreted as `B 9sus`:

```js
Chord.get('b9sus').intervals // =>  [ '1P', '4P', '5P', '7m', '9M' ]
```

Moreover `Cb9sus` is also mis-interpreted as `Cb 9sus`

```js
Chord.get('Cb9sus').intervals // => ['1P', '4P', '5P', '7m', '9M']
```
It only works with sharpened notes 😫

```js
Chord.get('C#b9sus').intervals // => ['1P', '4P', '5P', '7m', '9m']
```

The only solution is to pass the tonic and type separated:

```js
t.Chord.get(['C', 'b9sus']).intervals // =>  ['1P', '4P', '5P', '7m', '9m' ]
```

This is an argument to deprecate "combined names" and only accept tonic and type as separated arguments

Ideas?
