### ISSUE TITLE
Access packages such as new voicings in browser builds

### ISSUE THREAD

**Issue by Aduffy** [tonaljs/tonal#239]
It seems that the browser builds do not contain all of the packages? How would one get a browser built that includes for example the new Voicings packages?

**Comment by CarrierDirectStrick** [comment]
bump! I can't access the voicing package!

**Comment by danigb** [comment]
Yes. I was never happy with the Voices implementation (I think it get out of scope of `tonal` for the energy I can put on it). Probably I'll move it into an external repository (and module). Meanwhile, I'll keep this issue open

**Comment by stevage** [comment]
Is there any way to use the voicing package? It doesn't seem to be published on NPM. Using the source directly is a bit tricky as my project is JS. And I can't get it to build because of this error "You need to install typescript in your project".

Sorry, I don't mean to make work - Tonal is incredible, and I'm super appreciative for the work you have put into it.
