### ISSUE TITLE
Documentation update needed for Progressions

### ISSUE THREAD

**Issue by moxious** [tonaljs/tonal#244]
These docs: https://github.com/tonaljs/tonal/tree/master/packages/progression#progressionfromromannumeralskeytonic-string-chordprogression-string--string

state that to get a progression you need a first argument string; (keyTonic) this is not correct; the function takes a NoteLiteral, but there are not docs in place on how to create NoteLiterals, which are not type compatible with Notes.

**Comment by senritsu** [comment]
From what I gather from a quick look at the source, a `NoteLiteral` is just a union type of various ways to specify the `keyTonic`. You can specify 

- note name with octave like `'C4'`
- pitch class (without octave) like `'C'`
- a `Pitch` object (`{step, alt, oct?, dir?}`)
- a `Named` note object (`{name}`, where I assume `name` should be note name or pitch class)

Since `Note` itself extends `Pitch` and `Named`, everything seems to be working just fine. I assume the docs are mostly meant for the simplest case (hence just `string` is documented for the `keyTonic`), because exhaustively listing every possible way to pass a note might be a bit noisy if basically anything note-like goes.
