### ISSUE TITLE
error when trying to get TimeSignature with lower > 9

### ISSUE THREAD

**Issue by etiennedemoulin** [tonaljs/tonal#348]
> TimeSignature.get('12/10')
Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at parse (@tonaljs/time-signature/dist/index.js:62:19)
    at parse (@tonaljs/time-signature/dist/index.js:55:12)
    at Object.get (@tonaljs/time-signature/dist/index.js:48:20)

**Comment by danigb** [comment]
Of course, this should not throw in this case.

Said that, this is not an `irregular` time signature, but an `irrational one` (https://en.wikipedia.org/wiki/Time_signature#Irrational_meters). I was reluctant to introduce that kind of signatures because I think they are very artificial, very very rare, and could give the idea that any fraction is suitable for a time signature.

Anyway, since they are mentioned in wikipedia, I think we could implement it... thoughts?

**Comment by etiennedemoulin** [comment]
The lib throw the same way in case of 7/16, which is a « kind of normal » time signature.

I would be happy if the lib is not throwing in case of any fraction, so I can handle the error and say to the user that he’s doing something weird.
Btw : +1 on implementing irrational meters!
