### ISSUE TITLE
tonaljs/key melodic minor chord

### ISSUE THREAD

**Issue by senner007** [tonaljs/tonal#362]
Hi :)

Happy new years and thank you for making this library :)

**Issue:**
The Key.minorKey(key) returns melodic.chords [ (key)m6, ...]
I believe this should be mMaj7. 
Right?

**Comment by jrgm** [comment]
Yeah, I see what you mean. `Key.minorKey('A')` returns (simplified):
```
{
  "natural": {
    "scale": [ "A", "B", "C", "D", "E", "F", "G" ],
    "chords": [ "Am7", "Bm7b5", "Cmaj7", "Dm7", "Em7", "Fmaj7", "G7" ],
  },
  "harmonic": {
    "scale": [ "A", "B", "C", "D", "E", "F", "G#" ],
    "chords": [ "AmMaj7", "Bm7b5", "C+maj7", "Dm7", "E7", "Fmaj7", "G#o7" ],
  },
  "melodic": {
    "scale": [ "A", "B", "C", "D", "E", "F#", "G#" ],
    "chords": [ "Am6", "Bm7", "C+maj7", "D7", "E7", "F#m7b5", "G#m7b5" ],
  }
}
```
`A C E G#` is `AmMaj7`, but melodic.chords says it is `Am6`. `harmonic.chords` has it as `AmMaj7` for the same `A C E G#`.

**Comment by senner007** [comment]
Right and I believe that amMaj7 belongs to the key of am more than am6 since am6 could also be interpretted as f#m7b5/a

**Comment by danigb** [comment]
Hi,

Well, choosing a chord from a scale is not a exact science... I'd like to find the references (I tend to link to wikipedia if possible), but I can't find them in this case. Anyway, I think `Am6` is correct because it represents better the scale. With `AmMaj7` is not clear if we are on harmonic or melodic. However `Am6` is not part of the harmonic scale, so it's more representative of this minor scale.

I'm going to close the issue. But feel free to open if you still think is incorrect. Please provide some references, if any.
