### ISSUE TITLE
[Feature request] Unicode symbol list

### ISSUE THREAD

**Issue by eye-wave** [tonaljs/tonal#436]
i think a good package for this repo would be a list of music unicode symbols presented in a more accessible way. for example

```ts
export default {
  "G-Clef": {
    unicode: "U+1D11E",
    html: "&#119070;",
    css: "\1D11E",
    icon: "𝄞"
  }
}

```

**Comment by danigb** [comment]
Hey! I think this is outside the scope of tonal. Although the library looks like a "database" of things, I'd like to focus on "calculations" part. We can add two intervals (and that's not trivial and prone to bugs, that's why we use a library) but I don't think we can manipulate unicode symbols.

Anyway, I think is a good idea and encourage you to create a npm package for it.

Thanks!
