### ISSUE TITLE
m6 chords should not include 4th degree

### ISSUE THREAD

**Issue by felixroos** [tonaljs/tonal#97]
**Describe the bug**

```js
Chord.notes("Cm6")
``` 

returns 

```json
["C", "Eb", "F", "G", "A"]
````

The fourth degree (in this case F) is not part of a minor 6 chord.

**Expected behavior**
should return

```json
["C", "Eb", "G", "A"]
````

**Additional context**
https://github.com/danigb/tonal/blob/bb72df5fceac29a53d9fea52d16e137ad83f7b2f/packages/dictionary/data/chords.json#L94 > P4 should be removed

see e.g.
https://en.wikibooks.org/wiki/Music_Theory/Complete_List_of_Chord_Patterns#Minor

**Comment by danigb** [comment]
You're right. Thanks! Would you like to make a PR?

**Comment by felixroos** [comment]
Okay!

**Comment by danigb** [comment]
Hi @felixroos 

First of all, thanks a lot for the PR. I've decided not to merge it because of the formatting problems and, address one of the annoying problems of this project: the complex infrastructure.

I've created a new v3 release that you can take a look here: https://github.com/danigb/tonal/tree/feat/v3 where the issue is resolved.

Thanks again!

**Comment by danigb** [comment]
Fixed at v3! Thanks again for reporting! 👍
